# Generated by Django 3.0.5 on 2020-04-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('imageTitle', models.CharField(max_length=300)),
            ],
        ),
    ]
