# Generated by Django 3.0.5 on 2020-04-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0005_painting_museum_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.CharField(default='United States', max_length=100),
            preserve_default=False,
        ),
    ]
