# Generated by Django 3.0.5 on 2020-04-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0006_artist_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='author_id',
            new_name='author',
        ),
    ]
