# Generated by Django 3.0.5 on 2020-04-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0008_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gallery.Genre'),
        ),
    ]
