# Generated by Django 3.0.5 on 2020-04-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0009_auto_20200430_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='portraitImageTitle',
            new_name='portraitImagePath',
        ),
        migrations.RenameField(
            model_name='museum',
            old_name='imageTitle',
            new_name='imagePath',
        ),
        migrations.RenameField(
            model_name='painting',
            old_name='imageTitle',
            new_name='imagePath',
        ),
    ]
