# Generated by Django 3.0.5 on 2020-05-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0012_museum_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='museum',
            old_name='imagePath',
            new_name='appearenceImagePath',
        ),
        migrations.AddField(
            model_name='museum',
            name='logoImagePath',
            field=models.CharField(default='path', max_length=300),
            preserve_default=False,
        ),
    ]
