# Generated by Django 3.0.5 on 2020-05-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0015_auto_20200502_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='year',
            field=models.IntegerField(),
        ),
    ]
