# Generated by Django 3.0.5 on 2020-05-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0017_auto_20200502_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
