# Generated by Django 3.0.5 on 2020-05-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0018_auto_20200518_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='biography',
            field=models.CharField(default='SET', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='link',
            field=models.CharField(default='VALUE', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='link',
            field=models.CharField(default='COMM', max_length=500),
            preserve_default=False,
        ),
    ]
